apps/courses/urls.py
#!/usr/bin/env python3
#-*- coding: utf-8 -*-


__author__ = 'huang'
__time__ = '2018/3/15 13:10'

from courses.views import CourseListView, CourseDetailView, CourseInfoView, CommentsView, AddCommentsView, VideoPlayView
from django.urls import path, re_path

app_name = 'courses'

urlpatterns = [
    # 课程列表
    path('list/', CourseListView.as_view(), name='list'),
    # 课程详情
    re_path('course/(?P<course_id>\d+)/', CourseDetailView.as_view(), name="course_detail"),
    # 课程章节列表
    re_path('info/(?P<course_id>\d+)/', CourseInfoView.as_view(), name='course_info'),
    # 课程评论
    re_path('comments/(?P<course_id>\d+)/', CommentsView.as_view(), name="course_comments"),
    # 添加课程评论
    path('add_comment/', AddCommentsView.as_view(), name="add_comment"),
    # 视频信息
    re_path('video/(?P<course_id>\d+)/', VideoPlayView.as_view(), name="video_play"),
]

apps/organization/urls.py
#!/usr/bin/env python3
#-*- coding: utf-8 -*-
__author__ = 'huang'
__time__ = '2018/3/14 16:20'
from organization.views import OrgListView, OrgHomeView, OrgCourseView, OrgTeacherView, OrgDescView, AddFavView, \
    TeacherListView, TeacherDescView

from django.urls import path, re_path

app_name = 'organization'
urlpatterns = [
    # 课程机构列表
    path('list/', OrgListView.as_view(), name='org_list'),
    # 机构首页
    re_path('home/(?P<org_id>\d+)/', OrgHomeView.as_view(), name="org_home"),
    # 访问课程
    re_path('course/(?P<org_id>\d+)/', OrgCourseView.as_view(), name="org_course"),
    # 访问机构描述
    re_path('desc/(?P<org_id>\d+)/', OrgDescView.as_view(), name="org_desc"),
    # 访问机构讲师
    re_path('teacher/(?P<org_id>\d+)/', OrgTeacherView.as_view(), name="org_teacher"),
    # 添加收藏
    path('add_fav/', AddFavView.as_view(), name="add_fav"),
    # 访问讲师列表
    path('teacher_list/', TeacherListView.as_view(), name="teacher_list"),
    # 教师详情
    re_path('teacher/detail/(?P<teacher_id>\d+)/', TeacherDescView.as_view(), name="teacher_detail"),
   ]

apps/users/urls.py
#!/usr/bin/env python3
#-*- coding: utf-8 -*-
from users.views import UserInfoView, UpdateImageView, UpdatePWDView, SendEmailView, UpdateEmailView, UserCourseView, \
    MyMessageView
from users.views import FavCourseView, FavOrgView, FavTeacherView
__author__ = 'huang'
__time__ = '2018/3/17 16:14'

from django.urls import path, re_path
app_name = 'users'

urlpatterns = [
    # 用户详情
    path('info/', UserInfoView.as_view(), name='user_info'),
    # 更新用户头像
    path('update/image/', UpdateImageView.as_view(), name='update_image'),
    # 更新用户密码
    path('update/password/', UpdatePWDView.as_view(), name='update_pwd'),
    # 发送更改邮箱的验证码
    path('send_email_code/', SendEmailView.as_view(), name='send_email_code'),
    # 重设邮箱
    path('update_email/', UpdateEmailView.as_view(), name="update_email"),
    # 用户课程列表
    path('courses/', UserCourseView.as_view(), name='user_course'),
    # 用户消息页
    path('message/', MyMessageView.as_view(), name='user_massage'),
    # 用户收藏的各类
    path('fav_course/', FavCourseView.as_view(), name='fav_course'),
    path('fav_org/', FavOrgView.as_view(), name='fav_org'),
    path('fav_teacher/', FavTeacherView.as_view(), name='fav_teacher'),

]

djangoplan/urls.py
from django.urls import path, include, re_path
from django.views.static import serve

import xadmin
from djangoplan.settings import MEDIA_ROOT, STATIC_ROOT
from users.views import LoginView, RegisterView, ActiveUserView, ForgetPWDView, ResetView, ModifyPwdView, LogoutView, \
    IndexView

# 全局404页面配置
handler404 = 'users.views.page_not_found'
handler403 = 'users.views.page_is_403'
handler500 = 'users.views.page_is_500'
urlpatterns = [
    path('xadmin/', xadmin.site.urls),
    # TemplateView.as_view会将template转换为view
    path('', IndexView.as_view(), name='index'),
    # 注册登录等用户相关 ↓↓↓↓ #
    # 登录界面
    path('login/',  LoginView.as_view(), name='login'),
    # 登出界面
    path('logout/', LogoutView.as_view(), name="logout"),
    # 注册界面
    path('register/', RegisterView.as_view(), name='register'),
    # 验证码
    path("captcha/", include('captcha.urls')),
    # 验证激活是否成功
    re_path('active/(?P<active_code>.*)/', ActiveUserView.as_view(), name="user_active"),
    # 忘记密码验证
    path('forget_pwd/', ForgetPWDView.as_view(), name='forget_pwd'),
    # 重设密码
    re_path('reset/(?P<active_code>.*)/', ResetView.as_view(), name="reset_pwd"),
    # 重设成功
    path('modify_pwd/', ModifyPwdView.as_view(), name="modify_pwd"),
    # 注册登录等用户相关 ↑↑↑↑ #
    # 机构显示
    # path('org_list/', OrgView.as_view(), name='org_list'),
    path('org/', include('organization.urls', namespace='org')),
    # 图片处理,使用django自带的serve告诉他去哪里找
    re_path('media/(?P<path>.*)', serve, {"document_root": MEDIA_ROOT}),
    # 媒体处理,
    re_path('static/(?P<path>.*)', serve, {"document_root": STATIC_ROOT}),
    # 课程处理
    path('course/', include('courses.urls', namespace='course')),
    # 用户信息处理
    path('user/', include('users.urls', namespace='user')),
]

apps/courses/models.py
from django.db import models
#from datetime import datetime
from django.utils import timezone as datetime
# Create your models here.


# 课程信息
from organization.models import CourseOrg, Teacher


class Course(models.Model):
    # 课程等级
    DEGREE_CHOICES = (
        ('cj', u'初级'),
        ('zj', u'中级'),
        ('gj', u'高级'),
    )
    teacher = models.ForeignKey(Teacher, verbose_name=u"讲师", on_delete=models.CASCADE, null=True, blank=True)
    course_org = models.ForeignKey(CourseOrg, on_delete=models.CASCADE, verbose_name=u"所属机构", null=True, blank=True)
    name = models.CharField(max_length=50, verbose_name=u'课程名')
    desc = models.CharField(max_length=300, verbose_name=u'课程描述')
    # textfield可以不输入长度，输入可以无限长,教程说之后改为富文本
    detail = models.TextField(verbose_name=u'课程详情')
    # 课程等级
    degree = models.CharField(choices=DEGREE_CHOICES, max_length=2)
    # 使用分钟数做后台记录，前台转换
    learn_times = models.IntegerField(default=0, verbose_name=u'学习时长（分钟）')
    # 点击开始学习就计算人数
    students = models.IntegerField(default=0, verbose_name=u'学习人数')
    fav_nums = models.IntegerField(default=0, verbose_name=u'收藏人数')
    is_banner = models.BooleanField(default=False, verbose_name=u"是否轮播")
    tag = models.CharField(max_length=15, verbose_name=u"课程标签", default=u"")
    image = models.ImageField(
        upload_to='courses/%Y/%m',
        verbose_name=u'封面图',
        max_length=100
    )
    # 保存点击量，点一下就算
    click_nums = models.IntegerField(default=0, verbose_name=u'点击数')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')
    category = models.CharField(max_length=20, default=u"", verbose_name=u"课程类别")

    def get_zj_nums(self):
        # 获取章节数
        return self.lesson_set.all().count()

    def get_learn_users(self):
        # 谁的里面添加了它做外键，他都可以取出来
        # 获取学习的人
        return self.usercourse_set.all()[:5]

    class Meta:
        verbose_name = u'课程'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '《{0}》'.format(self.name)


# 章节信息
class Lesson(models.Model):
    # 因为一个课程对应许多章节，所以章节表中课程为外键
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name=u'课程')
    name = models.CharField(max_length=100, verbose_name=u'章节名')
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')
    # 后台显示名称

    class Meta:
        verbose_name = u'章节'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '《{0}》课程的《{1}》章节'.format(self.course, self.name)


# 视频信息
class Video(models.Model):
    # 一个章节对应多个视频，所以章节为视频的外键
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, verbose_name=u'章节')
    name = models.CharField(max_length=100, verbose_name=u'视频名')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')
    url = models.CharField(max_length=200, default="http://www.ihave20sp.xyz/", verbose_name=u"访问地址")
    learn_times = models.IntegerField(default=0, verbose_name=u"学习时长(分钟数)")
    class Meta:
        verbose_name = u'视频'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '{0}章，{1}'.format(self.lesson, self.name)


# 课程资源
class CourseResource(models.Model):
    # 因为一个课程对应很多资源，所以课程设置为外键
    course = models.ForeignKey(Course, on_delete=models.CASCADE, verbose_name=u'课程')
    name = models.CharField(max_length=100, verbose_name=u'名称')
    # 定义成文件类型，后台会有上次按钮
    # FileField 要求最大长度
    download = models.FileField(
        upload_to='course/resourse/%Y/%m',
        verbose_name=u'资源文件',
        max_length=100)
    add_time = models.DateTimeField(default=datetime.now, verbose_name=u'添加时间')

    class Meta:
        verbose_name = u'课程资源'
        verbose_name_plural = verbose_name

    def __str__(self):
        return '《{0}》课程的{1}文件'.format(self.course, self.name)

templates/base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% block custom_css %} {% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-3.3.1.min.js' %}" type="text/javascript"></script>
    {% block costom_js %} {% endblock %}

</head>
<body>
<section class="headerwrap ">
    <header>
		<div  class=" header">
 			<div class="top">
				{% if request.user.is_authenticated %}
            <div class="wp">
             <div class="fl"><p>服务电话：<b>23333333</b></p></div>
			<div class="personal">

                            <dl class="user fr">
                                <dd>{{ user.username }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ user.image }}"/></dt>
                            </dl>
                            <div class="userdetail">
                            	<dl>
	                                <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ user.image }}"/></dt>
	                                <dd>
	                                    <h2>{{ user.nick_name }}</h2>
	                                    <p>{{ user.username }}</p>
	                                </dd>
                                </dl>
                                <div class="btn">
	                                <a class="personcenter fl" href="{% url 'users:user_info' %}">进入个人中心</a>
	                                <a class="fr" href="{% url 'logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
              <a href="{% url 'users:user_massage' %}">
                            <div class="msg-num"><span id="MsgNum">未读消息{{ request.user.unread_nums }}</span></div>
                        </a>
            </div>
    {% else %}
                    				<div class="wp">
					<div class="fl"><p>服务电话：<b>23333</b></p></div>
					<!--登录后跳转-->


                      <a style="color:white" class="fr registerbtn" href="{% url "register" %}">注册</a>
                    <a style="color:white" class="fr loginbtn" href="{% url 'login' %}?next={{ request.path }}">登录</a>




				</div>
{% endif %}
			</div>

            <div class="middle">
                <div class="wp">
                    <a href="{% url 'index' %}"><img class="fl" src="{% static 'images/logo.jpg' %}"/></a>
                    <div class="searchbox fr">
                        <div class="selectContainer fl">
                             <span class="selectOption" id="jsSelectOption" {% ifequal  '/' request.path %}data-value="course"> 公开课{% endifequal %}{% ifequal  '/course' request.path|slice:":7" %}data-value="course"> 公开课 {% endifequal %}{% ifequal  '/org/teacher' request.path|slice:":12" %}data-value="teacher"> 授课教师{% endifequal %}{% ifequal  '/org/list' request.path|slice:":9" %}data-value="org"> 课程机构{% endifequal %}</span>
                            <ul class="selectMenu" id="jsSelectMenu">
                                <li data-value="course">公开课</li>
                                <li data-value="org">课程机构</li>
                                <li data-value="teacher">授课教师</li>
                            </ul>
                        </div>
                        <input id="search_keywords" class="fl" type="text" value="" placeholder="请输入搜索内容"/>
                        <img class="search_btn fr" id="jsSearchBtn" src="{% static 'images/search_btn.png' %}"/>
                    </div>
                </div>
            </div>


			<nav>
				<div class="nav">
					<div class="wp">
						<ul>
							<li {% ifequal  '/' request.path %}
							 class="active"
							{% endifequal %}><a href="{% url 'index' %}">首页</a></li>
							<li  {% ifequal  '/course' request.path|slice:":7" %}
							 class="active"
							{% endifequal %}>
								<a href="{% url 'course:list' %}">
									公开课<img class="hot" src="{% static 'images/nav_hot.png' %}">
								</a>
							</li>
							<li {% ifequal  '/org/teacher' request.path|slice:":12" %}
							 class="active"
							{% endifequal %}>
								<a href="{% url 'org:teacher_list' %}">授课教师</a>
							</li>
							<li {% ifequal  '/org/list' request.path|slice:":9" %}
							 class="active"
							{% endifequal %}><a href="{% url 'org:org_list' %}">课程机构</a></li>
						</ul>
					</div>
				</div>
			</nav>

			</div>
    </header>
</section>
<!--crumbs start-->
{% block custom_bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block content %}
{% endblock %}

<footer>
		<div class="footer">
			<div class="wp">
				<ul class="cont">
					<li class="logo"><a href="{% url 'index' %}"><img src="{% static 'images/footlogo.png' %}"/></a></li>
					<li class="third"><img class="fl" src="{% static 'images/tell.png' %}"/><p class="tell">23333333</p><p class="time">周一至周日 9:00-18:00</p></li>
				</ul>

			</div>
			<p class="line"></p>
			<div class="wp clear">
                <span class="fl">©2018 ihave20sp.xyz 用于个人学习 保留所有权利</span>
                <span class="fr">copyright© 2018 ICP备案证书号：<a style="color:#717171 " href="http://www.miitbeian.gov.cn/">豫ICP备18008601号-1</a></span>
			</div>
		</div>
	</footer>

<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=953743087&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>

<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script src="{% static 'js/deco-common.js' %}" type='text/javascript'></script>
<script src="{% static 'js/plugins/laydate/laydate.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>
<script src="{% static 'js/unslider.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/jquery.scrollLoading.js' %}"  type="text/javascript"></script>
<script src="{% static 'js/deco-common.js' %}"  type="text/javascript"></script>
{% block custom_js %} {% endblock %}
</body>
</html>

templates/org_base.html
<!DOCTYPE html>
<html>
{% load staticfiles %}
<head>
	<meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1" >
	<title>{% block title %}机构首页{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/animate.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'js/plugins/queryCity/css/cityLayout.css' %}">
    {% block custom_css %} {% endblock %}
    <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/jquery-migrate-1.2.1.min.js' %}" type="text/javascript"></script>
    {% block custom_js %} {% endblock %}
</head>
<body>
<section class="headerwrap ">
    <header>
		<div  class=" header">
                <div class="top">
				{% if request.user.is_authenticated %}
            <div class="wp">
             <div class="fl"><p><a href="{% url 'index' %}" style="color: #00a0f0">首页 </a>服务电话：<b>23333333</b></p></div>
			<div class="personal">

                            <dl class="user fr">
                                <dd>{{ user.username }}<img class="down fr" src="{% static 'images/top_down.png' %}"/></dd>
                                <dt><img width="20" height="20" src="{{ MEDIA_URL }}{{ user.image }}"/></dt>
                            </dl>
                            <div class="userdetail">
                            	<dl>
	                                <dt><img width="80" height="80" src="{{ MEDIA_URL }}{{ user.image }}"/></dt>
	                                <dd>
	                                    <h2>{{ user.nick_name }}</h2>
	                                    <p>{{ user.username }}</p>
	                                </dd>
                                </dl>
                                <div class="btn">
	                                <a class="personcenter fl" href="{% url 'users:user_info' %}">进入个人中心</a>
	                                <a class="fr" href="{% url 'logout' %}">退出</a>
                                </div>
                            </div>
                        </div>
              <a href="{% url 'users:user_massage' %}">
                            <div class="msg-num"><span id="MsgNum">未读消息{{ request.user.unread_nums }}</span></div>
                        </a>
            </div>
    {% else %}
                    				<div class="wp">
					<div class="fl"><p>服务电话：<b>23333</b></p></div>
					<!--登录后跳转-->


                      <a style="color:white" class="fr registerbtn" href="{% url "register" %}">注册</a>
                    <a style="color:white" class="fr loginbtn" href="{% url 'login'%}?next={{ request.path }}">登录</a>




				</div>
{% endif %}
			</div>


    <div class="middle companyheader">
        <div class="wp">
            <img class="fl" style="width: 112px;height: 103px" src="{% static 'media/org/2016/11/imooc.png' %}"/>
            <div class="head fl">
                <h1>

                    <img src="{% static 'images/authentication.png' %}"/>
                    <img src="{% static 'images/gold.png' %}"/>
                </h1>
                <p class="fl">
                    <span class="fl" style="margin-top:8px;color:#848484;">推荐指数： </span>
                    <span class="precision company-credit" data-star-scope="5.0"></span>
                    <span class="key">5.0</span>
                </p>
            </div>
            <div class="btn fr collectionbtn  notlogin
                 "data-favid="22" data-fav-type="1">
                 {% if has_fav %}
                    已收藏
                {% else %}
                    未收藏
                {% endif %}
            </div>

        </div>
    </div>
			</div>
    </header>
</section>

{% block beard %}
{% endblock %}

<section>
	<div class="wp list personal_list comp">
		<div class="left">
			<ul>
				<li class="{% ifequal  '/org/home' request.path|slice:":9" %}active2{% endifequal %}"><a href="{% url 'org:org_home' org.id %}">机构首页</a></li>
                <li class="{% ifequal  '/org/course' request.path|slice:":11" %}active2{% endifequal %}"><a href="{% url 'org:org_course' org.id %}">机构课程</a></li>
                <li class="{% ifequal  '/org/desc' request.path|slice:":9" %}active2{% endifequal %}"><a href="{% url 'org:org_desc' org.id %}">机构介绍</a></li>
                <li class="{% ifequal  '/org/teacher' request.path|slice:":12" %}active2{% endifequal %}"><a href="{% url 'org:org_teacher' org.id %}">机构讲师</a></li>
			</ul>
		</div>
{% block right_form %}

{% endblock %}

</section>
<!--sidebar start-->
<section>
    <ul class="sidebar">
        <li class="qq">
            <a target="_blank" href="http://wpa.qq.com/msgrd?v=3&uin=953743087&site=qq&menu=yes"></a>
        </li>
        <li class="totop"></li>
    </ul>
</section>
<!--sidebar end-->
<!--header start-->
</div>
<!--弹出省省市-->
<script src="{% static 'js/selectUi.js' %}" type='text/javascript'></script>
<script type="text/javascript" src="{% static 'js/plugins/laydate/laydate.js' %}"></script>
<script src="{% static 'js/plugins/layer/layer.js' %}"></script>
<script src="{% static 'js/plugins/queryCity/js/public.js' %}" type="text/javascript"></script>

<script type="text/javascript" src="{% static 'js/plugins/jquery.raty.js' %}"></script>
<script type="text/javascript">
    //收藏分享
//收藏分享
function add_fav(current_elem, fav_id, fav_type){
    $.ajax({
        cache: false,
        type: "POST",
        url:"/org/add_fav/",
        data:{'fav_id':fav_id, 'fav_type':fav_type},
        async: true,
        beforeSend:function(xhr, settings){
            xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
        },
        success: function(data) {
            if(data.status == 'fail'){
                if(data.msg == '用户未登录'){
                    window.location.href="login.html";
                }else{
                    alert(data.msg)
                }

            }else if(data.status == 'success'){
                current_elem.text(data.msg)
            }
        },
    });
}

$('.collectionbtn').on('click', function(){
    add_fav($(this), {{ course_org.id }}, 2);
});

$(function(){
    var $precision = $('.precision'),
        score = $precision.attr('data-star-scope'),
        option =  {
                    half		: true,
                    path		: {% static "images/" %},
                    precision	: true,
                    size		: 24,
                    starOff		: 'g_star.png',
                    starOn		: 'r_star.png',
                    starHalf	: 'h_star.png',
                    hints       : ['极差', '差', '一般', '好评', '非常满意'],
                    noRatedMsg  : '暂时还未获得评价！',
                    readOnly    : true,
                    score       : score
                };
    $precision.raty(option);

    $('.jsFavBtn').on('click', function(){
        var type = $(this).attr('data-fav-type');
        if(type == '1'){
            favPraise($(this), 'fav' ,1 , '收藏');

        }else if(type == '3'){
            favPraise($(this), 'fav' ,3 );

        }else if(type == '11'){
            favPraise($(this), 'pra', 1);

        }else if(type == '4'){
            favPraise($(this), 'fav' ,4 );

        }
    });
})
</script>


<script type="text/javascript">
$(function() {
    $('.recordbtn1').click(function(){
        $('.recordbox1').show();
    });
    $('.recordbtn2').click(function(){
        $('.recordbox2').show();
    });

    $('.imgslide').unslider({
        speed: 500,               //  The speed to animate each slide (in milliseconds)
        delay: 3000,              //  The delay between slide animations (in milliseconds)
        complete: function() {},  //  A function that gets called after every slide animation
        keys: true,               //  Enable keyboard (left, right) arrow shortcuts
        dots: true,               //  Display dot navigation
        fluid: false              //  Support responsive design. May break non-responsive designs
    });
    var unslider = $('.imgslide').unslider();
    $('.unslider-arrow').click(function() {
        var fn = this.className.split(' ')[1];
        unslider.data('unslider')[fn]();
    });
});
</script>

</body>
</html>

templates/usercenter-fav-course.html
{% extends 'usercenter-base.html' %}
{% load staticfiles %}
{% block title %}我收藏的课程|huang的练习{% endblock %}
{% block beard %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'user:user_info' %}">个人中心</a>></li>
                <li>我的收藏</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block count %}
    <div class="right" >
            <div class="personal_des Releasecont">
                <div class="head">
                    <h1>我的收藏</h1>
                </div>
            </div>
            <div class="personal_des permessage">
                <div class="head">
                    <ul class="tab_header messagehead">
                        <li><a href="{% url 'user:fav_org' %}">课程机构</a> </li>
                        <li><a href="{% url 'user:fav_teacher' %}">授课教师 </a></li>
                        <li class="active"><a href="{% url 'user:fav_course' %}">公开课程</a></li>
                    </ul>

                </div>
                <div class="companycenter">
                    <div class="group_list brief">
                        {% for course in course_list %}
                        <div class="module1_5 box">
                            <a href="{% url 'course:course_detail' course.id %}">
                                <img width="214" height="190" src="{{ MEDIA_URL }}{{ course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="course-detail.html"><h2>{{ course.name }}</h2></a>
                                <span class="fl">时长：<i class="key">{{ course.learn_times }}</i></span>
                                <span class="fr">学习人数：{{ course.student }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.course_org.name }}</span>
                                <span class="delete-group fr jsDeleteFav_course" data-favid="{{ course.id }}"></span>
                            </div>
                        </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
{% endblock %}

templates/usercenter-mycourse.html
{% extends 'usercenter-base.html' %}
{% load staticfiles %}
{% block title %}我的课程|huang的练习{% endblock %}


<!--crumbs start-->
{% block beard %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'user:user_info' %}">个人中心</a>></li>
                <li>我的课程</li>
            </ul>
        </div>
    </section>
{% endblock %}



{% block count %}
    <div class="right" >
		<div class="personal_des Releasecont">
			<div class="head">
				<h1>我的课程</h1>
			</div>
		</div>
		<div class="personal_des permessage">
			<div class="companycenter">
				<div class="group_list brief">
                    {% for course in user_courses %}
                    <div class="module1_5 box">
                            <a href="{% url 'course:course_detail' course.id %}">
                                <img width="214" height="190" class="scrollLoading" src="{{ MEDIA_URL }}{{ course.image }}"/>
                            </a>
                            <div class="des">
                                <a href="course-detail.html"><h2>{{ course.name }}</h2></a>
                                <span class="fl">课时：<i class="key">{{ course.learn }}</i></span>
                                <span class="fr">学习人数：{{ course.student }}</span>
                            </div>
                            <div class="bottom">
                                <span class="fl">{{ course.course_org.name }}</span>
                                <span class="star fr  notlogin" data-favid="15">{{ course.fav_nums }}</span>
                            </div>
                        </div>
                    {% endfor %}

				</div>
			</div>
		</div>
	</div>
{% endblock %}